"""auto gen

Revision ID: c8f5a42e63ce
Revises: 72b6d58a9259
Create Date: 2024-03-08 12:08:12.682199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f5a42e63ce'
down_revision: Union[str, None] = '72b6d58a9259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    # op.add_column('posts', sa.Column('published', sa.Boolean(), server_default='True', nullable=False))
    # op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_column('posts', 'owner_id')
    # op.drop_column('posts', 'created_at')
    # op.drop_column('posts', 'published')
    # op.drop_column('posts', 'content')
    # ### end Alembic commands ###
